name: Test shell

on:
  push:
    branches:
      - "**"
    paths:
      - "apps/shell/**"

env:
  APP_NAME: shell

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --workspace=$APP_NAME --ignore-scripts

      - name: Run tests
        run: npm test --workspace=$APP_NAME
