name: Test mfa-menu

on:
  push:
    branches:
      - "**"
    paths:
      - "apps/mfa-menu/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --workspace=mfa-menu --ignore-scripts

      - name: Run tests
        run: npm test --workspace=mfa-menu
